Weather features
jacoor/testowanie-api pull request #2
Opened 2023-06-19 22:17 UTC by michalkrzem

magic

2023-06-21 17:13 UTC, jacoor requested changes

2023-06-21 17:13 UTC, jacoor commented on Pipfile
> +pandas = "*"
It's a good practice to use version lock on packages, like with requests above.
How to find version? It's in lock file or use `pip list` command. 
Please update

2023-06-21 17:13 UTC, jacoor commented on imgw_api/tests/test_get_imgw_api_data.py
> +
I'd mark those tests in name as exploration tests, since you are calling external APIs here.

2023-06-23 22:02 UTC, michalkrzem commented on Pipfile
> +pandas = "*"
I added version numbers

2023-06-24 06:55 UTC, jacoor approved these changes
Nice! Now merge when ready.
The idea is that the creator of the PR should merge it, because he knows if it will not interfere with other work (ie. QA). But that depends from team to team.

2023-06-25 20:42 UTC, merged